Update leg sense organs
FlyBase/drosophila-anatomy-developmental-ontology pull request #1119
Opened 2021-04-30 12:34 UTC by gouttegd

Update sensory organs of legs based on new data from Kuan et al. (2020) (FBrf0247324).

Related to #1099

2021-04-30 14:32 UTC, Clare72 requested changes
mostly good, main thing is to change all the 'mechanosensory neuron of leg campaniform sensillum' terms (including the old ones) to use 'mechanosensory neuron'.

2021-04-30 14:32 UTC, Clare72 commented on src/ontology/fbbt-edit.obo
> +name: prothoracic coxal strand receptor
I would put 'neuron' on the end of this for clarity.

2021-04-30 14:32 UTC, Clare72 commented on src/ontology/fbbt-edit.obo
> +def: "A neuron with a cell body in the ventral nerve cord and a sensory dendrite terminating at the cuticle of the prothoracic coxa. There is one such neuron per prothoracic leg. It may be analog to
'It may be analog to' -> 'It may be analogous to' or 'It may be an analog to'

2021-04-30 14:49 UTC, gouttegd commented on src/ontology/fbbt-edit.obo
> +intersection_of: FBbt:00048057 ! sensory neuron of campaniform sensillum
> if you don't mind doing this?

No problem.

2021-05-04 13:37 UTC, Clare72 approved these changes
I also edited the logical definition on the parent class 'mechanosensory neuron of leg campaniform sensillum'.
You can merge when checks pass

2021-05-04 14:02 UTC, merged