Fix terms for taste neurons of taste bristles
FlyBase/drosophila-anatomy-developmental-ontology pull request #1228
Opened 2021-08-16 10:00 UTC by gouttegd

This PR attempts the issue with the `S cell`, `W cell`, `L1 GRN`, and `L2 GRN` terms being defined as labellar-specific gustatory neurons even though they are used in the literature, and in some curation records, with a broader meaning valid for gustatory neurons in *any* taste bristle.

The approach (here for the `S cell` term) is basically to introduce an intermediate term between `sugar-sensing neuron` (referring to any such neuron, regardless of which structure it belongs to) and `sugar-sensing neuron of the labellum`, to represent sugar-sensing neurons that belong to (or rather, innervate) a taste bristle. That new term is the one carrying the EXACT `S cell` synonym, matching the current usage in the literature. The same approach is used for the other three types of gustatory neurons.

To account for the different ways the existing terms have been used in curation records:
* the current `S cell` term becomes the new `sugar-sensing neuron of taste bristle`, and `sugar-sensing neuron of the labellum` is a new term;
* likewise, the current `L2 GRN` term becomes the new `high salt-sensing neuron of taste bristle`, and `high salt-sensing neuron of the labellum` is a new term;
* the current `W cell` becomes `water-sensing neuron of the labellum` (so, keeping its labellar-specific meaning), and the parent `water-sensing neuron of taste bristle` is a new term;
* likewise for `L1 GRN`.

related to #1190

2021-08-16 11:27 UTC, Clare72 requested changes
Probably worth looking at this (and maybe other) more recent reference(s) - FBrf0229608. It doesn't look as though low salt (appetitive) and water neurons exist outside of the labellum (so no need for parent classes). High salt is detected by some of the bitter neurons, rather than bitter being a subclass of a broader salt-detecting class.

2021-08-16 11:27 UTC, Clare72 commented on src/ontology/fbbt-edit.obo
> +def: "A high salt-sensing neuron that innervates a short or long sensillum of the labellum (Montell, 2009)." [FlyBase:FBrf0208984]
These are a subset of the labellar bitter-sensing neurons - the bitter neurons in S-a and S-b sensilla. From FBrf0229608:
>Bitter taste neurons in S-type sensilla also respond to high concentrations of salt

2021-08-16 11:27 UTC, Clare72 commented on src/ontology/fbbt-edit.obo
> +def: "A low salt-sensing neuron that innervates a short or long sensillum of the labellum (Montell, 2009)." [FlyBase:FBrf0208984]
looks like it is only long sensilla based on FBrf0229608, so this can be updated

2021-08-16 12:55 UTC, gouttegd commented on src/ontology/fbbt-edit.obo
> +name: water-sensing neuron of taste bristle
They do according to at least one paper (FBrf0160792). Interesting that a recent review does not mention them, I'll have another look before going forward here.

2021-08-16 12:56 UTC, gouttegd commented on src/ontology/fbbt-edit.obo
> +name: low salt-sensing neuron of taste bristle
Same as above, according to the same paper.

2021-08-16 13:46 UTC, Clare72 commented on src/ontology/fbbt-edit.obo
> +name: water-sensing neuron of taste bristle
Ah, it actually is in the figure, but not matched to the legend - looks like the functionality is not mapped to sensilla yet. Not clear if it is mapped to distict neurons yet either.

2021-08-24 10:54 UTC, gouttegd commented
Closing here as another PR is on the way to fix this issue.

2021-08-24 10:54 UTC, closed without merging